# Generated by Django 4.2.7 on 2026-04-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='e.g. 15.00 for 15%', max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount seller receives', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Total price paid by buyer', max_digits=10),
        ),
    ]
