# Generated by Django 4.2.7 on 2026-04-16 23:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_commission_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='Leave empty for an evergreen/infinite listing. Otherwise, set a quantity between 1 and 999.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
